### ISSUE TITLE
Row names

### ISSUE THREAD

**Issue by ACSoupir** [Syksy/curatedPCaData#23]
Weiner et al
- [x] `epic` missing row names (are numbers from somewhere?)
     - other studies seem fine

**Comment by Syksy** [comment]
All derived-variables (i.e. immune deconvolution methods, risk scores, AR score, ...) have been re-run latest on v0.7.8 and at least in internal inspection the data is consistent and not missing names and such. On some datasets (such as Barwick et al. & True et al.) not all deconvolution methods can be run due to lack of gene overlap, but this an underlying issue in the original data (due to the platform age pretty much).
