### ISSUE TITLE
Error: object 'wrapperOncoprintify' not found

### ISSUE THREAD

**Issue by jjacobi3** [Syksy/curatedPCaData#47]
Hello, following the vignette and it seems that the Oncoprintify wrapper is not found? I am using curatedPCaData_1.0.0

> taylor_oncoprint_1 <- curatedPCaData:::wrapperOncoprintify(mae_taylor, genes = genes)
Error: object 'wrapperOncoprintify' not found

Thanks!

**Comment by Syksy** [comment]
Hi @jjacobi3 ,

thanks for reporting this - our vignette shouldn't be using `curatedPCaData:::wrapperOncoprintify` because `:::` would indicate that  it's an internal function for the package (and shouldn't even be exposed to the user). If I remember right, this function was also removed during the Bioconductor review process from the package (as to focus on the data and its handling, rather than delve into analyses), but I can't recall right now exactly when. It shouldn't be part of the (Bioconductor) v1.0.0 though. The version v1.0.0 in Bioconductor does not have this function, nor does the vignette at the moment.

Could you perhaps clarify where did you download/compile the v1.0.0 that you're referring to?

I'd start off with re-installing using Bioconductor's `curatedPCaData` v1.0.0 `release` branch build with:
```
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("curatedPCaData")
```

The `devel` branch in Bioconductor has v1.1.1.

However, GitHub already has `curatedPCaData` v1.1.1, which would install with:
`devtools::install_github("Syksy/curatedPCaData")`

Could you please try reinstall with these, and/or help me reproduce your error with that function with description of which v1.0.0 you're referring to and where is it from? I did fresh installs from both Bioconductor and GitHub, and the package installs fine, and the vignette(s) don't have this function incorporated, so I can't right now reproduce your issue.

**Comment by jjacobi3** [comment]
Thanks so much for the quick response! 

I had originally installed from bioconductor about a month ago. I just installed the devtools version fine (1.1.1). 

I should have clarified in the previous post that I was working off the vignette from curatedPCaWorkflow on github:
https://github.com/Syksy/curatedPCaWorkflow/tree/main/vignettes/analyses.Rmd

That is probably the source of the error because the 'overview' vignette works great. So, is the workflow package not available anymore? 

Thanks!
-Justine

**Comment by Syksy** [comment]
Hi Justine,

ah, yes that makes sense, thanks for the clarification.
Indeed, there are two packages:
- `curatedPCaData`, of type `ExperimentData`, a Bioconductor-compatible package focused on providing the data.
- `curatedPCaWorkflow`, a package separated from original `curatedPCaData` during the `Bioconductor` peer-review with the package type `Workflow`. You have been following the latter's vignette.

Specifically, this separation was requested as in two major revision pointers when we first submitted `curatedPCaData` to Bioconductor:
`Please separate the analysis functionality from the infrastructure. The
package should only deliver the data to the user and demonstrate how to
obtain the data from ExperimentHub.`
and
`The demos in the vignettes should show the user how to obtain the data,
it does not necessarily need to show the user how to analyze it. The latter
would be more appropriate in a separate workflow package.`
in https://github.com/Bioconductor/Contributions/issues/3047#issuecomment-1591516244

We originally had 5+ vignettes, but the request was to pinpoint focus on data retrieval and its processing, rather than go, say, to oncoprint level (even though it's a visualization, one could argue it's very much an analysis as different genes' alteration percentages and somatic mutations are visualized, usually stratified by sample or patient subsets).

Thus, quite a large effort was put into separating `curatedPCaWorkflow` from `curatedPCaData`. The latter is the package you're currently working with, although it calls the data from `curatedPCaData`.

As there were two rounds of reviews, multiple other changes were requested on the way as well - including the request to change from our oncoprint function into a more generalized one, instead use e.g. `TCGAutils::oncoPrintTCGA` or oncoprints made available from `ComplexHeatmap`'s function [oncoprint](https://jokergoo.github.io/ComplexHeatmap-reference/book/oncoprint.html). The advantage in not having our own function is that everything shown in the analyses is more generalizable as we don't re-invent the wheel. I'd advise for the time being to look into these functions, and apply them to data provided in `curatedPCaData`

That being said, I apologize for the confusion regarding `curatedPCaWorkflow`. It is a separate package, and to be honest, I haven't just had the time to return back to fixing it, as it amounts to a huge quantity of work as the package(s) have been fundamentally altered. Therefore it is not advisable to follow vignettes currently provided in that package, as you noticed.

This is an appropriate notification of a vignette not working correctly, but would be more appropriate if it was attributed to `curatedPCaWorkflow` rather than `curatedPCaData`. 

Unfortunately my colleague who wrote that original oncoprintify function has moved to other projects, so it will take me a while to get to fixing this. I'd be glad to help with whatever you're working on with `curatedPCaData`, but I can't give a promised deadline on the legacy vignettes at `curatedPCaWorkflow` would be fully up to date again. Feel to pop me a message at teelaa@utu.fi if there's some specific task you're looking to do with the data.

If it is alright for you, I'd now close this issue, and open an analogous one in `curatedPCaWorkflow` regarding the state of the vignettes.

Thanks!
Daniel

**Comment by jjacobi3** [comment]
All sounds good- thanks for the response! Closing the issue.
