### ISSUE TITLE
To do list

### ISSUE THREAD

**Issue by jhcreed** [Syksy/curatedPCaData#5]
- [x] Clinical/pheno data for 3 example data sets (Sun, TCGA, Taylor)
- [x] Gene expression data for 3 example data sets (Sun, TCGA, Taylor)
- [x] CNA for 2 example data sets (TCGA and Taylor)
- [x] Align gene names across all data sets (for example using the same HUGO gene annotations for all datasets)
- [x] Wrappers for creating different kind of output (MAE, tibble)
- [x] Run xCell on 3 example data sets 
- [x] Create function for genetic scores (Decipher, Polaris, Oncotype)
- [ ] Create function for traditional risk scores (D'Amico, NICE, ...)
- [x] Fix "storing paths of more than 100 bytes is not portable" warnings with package building due to long file names/paths in Jim's legacy curation scripts

**Comment by Syksy** [comment]
Memo 13th Aug, 2020

- [x] All datasets to only include genes included in the original data, instead of having a larger union over all datasets
- [x] All datasets as MAEs, no duplication of having GEX/CNA etc separately
- [x] Make sure all datasets/platforms are in same direction (no need to transpose)
- [x] MAE-based vignette for using the package in its current format
- [x] For method comparisons (i.e. immune deconvolution), see for example https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6612828/

**Comment by Syksy** [comment]
Everything done with the exception of the traditional risk scores - their role remains to be discussed.
